In [1]:
from keras.models import load_model
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

Using TensorFlow backend.


In [2]:
model = load_model('TEST_93.h5')

In [7]:
testdata = pd.read_csv("test.csv")

In [4]:
testdata

Safety_Score  Days_Since_Inspection  Total_Safety_Complaints  \
0        19.497717                     16                        6   
1        58.173516                     15                        3   
2        33.287671                     15                        3   
3         3.287671                     21                        5   
4        10.867580                     18                        2   
...            ...                    ...                      ...   
2495     68.127854                      8                       11   
2496     54.840183                      9                        9   
2497     36.712329                     14                       10   
2498     38.721461                     13                       14   
2499     36.073059                     11                        1   

      Control_Metric  Turbulence_In_gforces  Cabin_Temperature  \
0          72.151322               0.388959              78.32   
1          64.585232               0.250841              78.60   
2          64.721969               0.336669              86.96   
3          66.362808               0.421775              80.86   
4          56.107566               0.313228              79.22   
...              ...                    ...                ...   
2495       49.680948               0.470819              77.80   
2496       71.194166               0.417087              79.77   
2497       91.203282               0.313950              83.96   
2498       73.154057               0.275003              77.38   
2499       60.665451               0.256250              84.56   

      Accident_Type_Code  Max_Elevation  Violations  Adverse_Weather_Metric  \
0                      4   37949.724386           2                0.069692   
1                      7   30194.805567           2                0.002777   
2                      6   17572.925484           1                0.004316   
3                      3   40209.186341           2                0.199990   
4                      2   35495.525408           2                0.483696   
...                  ...            ...         ...                     ...   
2495                   2   48251.586622           2                0.659387   
2496                   6   20761.984416           1                0.005010   
2497                   6   36676.100601           2                0.008629   
2498                   6   24211.359510           1                0.006247   
2499                   5   35920.146239           0                0.024409   

      Accident_ID  
0               1  
1              10  
2              14  
3              17  
4              21  
...           ...  
2495        12484  
2496        12487  
2497        12488  
2498        12491  
2499        12493  

[2500 rows x 11 columns]

In [17]:
scaled_x_tests = StandardScaler().fit(data).fit_transform(data)

In [9]:
scaled_x_tests

array([[-1.37172708,  0.86684517, -0.08007683, ...,  0.00903388,
        -0.46749271, -1.71741171],
       [ 1.0043842 ,  0.5829687 , -0.49801438, ...,  0.00903388,
        -0.64013842, -1.71491276],
       [-0.52451857,  0.5829687 , -0.49801438, ..., -0.97290955,
        -0.6361677 , -1.71380212],
       ...,
       [-0.31411911,  0.29909224,  0.47717323, ...,  0.00903388,
        -0.62504098,  1.74974078],
       [-0.19068475,  0.01521578,  1.03442329, ..., -0.97290955,
        -0.63118784,  1.75057376],
       [-0.35339367, -0.55253715, -0.77663941, ..., -1.95485297,
        -0.58432719,  1.75112908]])

In [10]:
total_class = ['Significant_Damage_And_Serious_Injuries',
 'Significant_Damage_And_Fatalities',
 'Highly_Fatal_And_Damaging',
 'Minor_Damage_And_Injuries']

In [11]:
classes = {}
for x in range(len(total_class)):
    classes[x] = total_class[x]

In [12]:
classes

{0: 'Significant_Damage_And_Serious_Injuries',
 1: 'Significant_Damage_And_Fatalities',
 2: 'Highly_Fatal_And_Damaging',
 3: 'Minor_Damage_And_Injuries'}

In [18]:
accident = []
severity = []
for i in range(len(scaled_data)):
    ids = 

SyntaxError: invalid syntax (<ipython-input-18-6766d86fe3b3>, line 4)

In [19]:
scaled_xdata[0,:].reshape(-1,11)

array([[-1.37172708,  0.86684517, -0.08007683,  0.59295729,  0.10913413,
        -0.61661954,  0.07798532,  0.58699497,  0.00903388, -0.46749271,
        -1.71741171]])

In [20]:
x = model.predict(scaled_xdata[0,:].reshape(-1,11))

In [21]:
x

array([[9.9999988e-01, 2.1271905e-16, 3.4867911e-14, 1.1478909e-07]],
      dtype=float32)

In [22]:
x.argmax()

0

In [23]:
classes[x.argmax()]

'Significant_Damage_And_Serious_Injuries'

In [24]:
scaled_xdata[0,-1]

-1.7174117092072527

In [25]:
ids  = []
output = []
for i in range(len(testdata)):
    pred_y = model.predict(np.array(scaled_x_tests[i,:]).reshape((-1,11)))
    ids.append(testdata.iloc[i,-1])
    output.append(classes[pred_y[0].argmax()])

In [26]:
final_data = pd.DataFrame({'Accident ID':ids,'Severity':output})

In [27]:
final_data.iloc[1,0]

10

In [28]:
final_data

Accident ID                                 Severity
0               1  Significant_Damage_And_Serious_Injuries
1              10                Highly_Fatal_And_Damaging
2              14                Minor_Damage_And_Injuries
3              17  Significant_Damage_And_Serious_Injuries
4              21                Highly_Fatal_And_Damaging
...           ...                                      ...
2495        12484  Significant_Damage_And_Serious_Injuries
2496        12487                Minor_Damage_And_Injuries
2497        12488                Minor_Damage_And_Injuries
2498        12491                Minor_Damage_And_Injuries
2499        12493  Significant_Damage_And_Serious_Injuries

[2500 rows x 2 columns]

In [29]:
final_data.to_csv('test_submission',index=False)